# Generated by Django 5.2.1 on 2025-05-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.FileField(upload_to='managers/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('academic', 'Академический руководитель'), ('manager', 'Менеджер программы')], max_length=20, verbose_name='Роль')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='DataBaseApp.page')),
            ],
        ),
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.FileField(upload_to='classmates/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates', to='DataBaseApp.page')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ОП')),
                ('program_link', models.URLField(verbose_name='Ссылка на ОП')),
                ('curriculum', models.TextField(verbose_name='Что я буду изучать')),
                ('skills', models.TextField(verbose_name='Чему научусь')),
                ('advantages', models.TextField(verbose_name='Преимущества программы')),
                ('prospects', models.TextField(verbose_name='Перспективы после обучения')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_info', to='DataBaseApp.page')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.FileField(upload_to='students/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('resume', models.TextField(verbose_name='Резюме')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='DataBaseApp.page')),
            ],
        ),
    ]
