# Generated by Django 5.2.1 on 2025-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на портфолио'),
        ),
    ]
