# Generated by Django 5.2.1 on 2025-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название профиля')),
                ('program_type', models.CharField(choices=[('B', 'Бакалавриат'), ('M', 'Магистратура'), ('S', 'Аспирантура'), ('AD', 'ДПО')], max_length=2, verbose_name='Тип профиля')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность (лет)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
            },
        ),
    ]
